events {
    worker_connections 1024;
}

http {
    upstream blue {
        server app-blue:3000;
    }

    upstream green {
        server app-green:3000;
    }

    # CAMBIAR AQUI: cambia "blue" a "green" para hacer el switch
    upstream active {
        server app-blue:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}