events {
    worker_connections 1024;
}

http {
    upstream blue {
        server app-blue:3000;
    }

    upstream green {
        server app-green:3000;
    }

    # CAMBIAR AQUI: cambia "app-blue" a "app-green" para hacer el switch
    upstream active {
        server app-blue:3000;
    }

    server {
        listen 80;

        # Frontend estático
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # API — proxea al upstream activo
        location /api/ {
            proxy_pass http://active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            proxy_pass http://active;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}