name: DevOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  debug-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ver estructura del proyecto
        run: |
          echo " Root:"
          ls -la
          echo " proyecto-devops:"
          ls -la proyecto-devops || echo "NO EXISTE"
          echo "proyecto-devops-green:"
          ls -la proyecto-devops-green || echo "NO EXISTE"

      - name: Ver Node y npm
        run: |
          node -v
          npm -v

      # ===== BLUE =====
      - name: Install dependencies (blue)
        working-directory: ./proyecto-devops
        run: npm install

      - name: Run tests (blue)
        working-directory: ./proyecto-devops
        run: npm test

      # ===== GREEN =====
      - name: Install dependencies (green)
        working-directory: ./proyecto-devops-green
        run: npm install

      - name: Run tests (green)
        working-directory: ./proyecto-devops-green
        run: npm test
